# Generated by Django 5.1.7 on 2025-03-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
