# Generated by Django 5.1.7 on 2025-03-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_gear_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
